# dclint disable service-image-require-explicit-tag
name: web-calc
services:
  app:
    image: oliviertremblaynoel/web-calc:latest
    volumes:
      - ${WEBCALC_CONFIG_VOL}=/root/.config/qalculate
    ports:
      - '0.0.0.0:80:80' # ttyd browser shell
