  name: CI
  on:
    push:
      branches: [ "main" ]
    schedule:
      - cron: '19 19 19 * *'
    workflow_dispatch:

  jobs:
    lint:
      runs-on: ubuntu-latest
      steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
      - uses: pre-commit/action@v3.0.1

    build:
      runs-on: ubuntu-latest
      needs: lint
      steps:
        - name: Checkout repo
          uses: actions/checkout@v4

        - name: Log in to DockerHub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build and push image
          uses: docker/build-push-action@v6
          with:
            platforms: linux/amd64,linux/arm64
            pull: true
            push: true
            tags: |
              ${{ secrets.DOCKERHUB_USERNAME }}/web-calc:latest
            cache-from: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/web-calc:buildcache
            cache-to: type=registry,ref=${{ secrets.DOCKERHUB_USERNAME }}/web-calc:buildcache,mode=max
            outputs: type=image,name=${{ secrets.DOCKERHUB_USERNAME }}/web-calc:latest,name-canonical=true
