name: CI
on:
  push:
    branches: [ "main" ]
  schedule:
    - cron: '19 19 19 * *'
  workflow_dispatch:

jobs:
  ci:
    uses: oliviertremblaynoel/gha-pipelines/.github/workflows/ci.yml@main
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
    with:
      PROJECT_NAME: ${{ github.event.repository.name }}
