name: Auto-merge Dependabot PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - labeled

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    steps:
    - uses: ahmadnassri/action-dependabot-auto-merge@v2
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
